"""Curated two- and three-token phrases recognized longest-first."""

PHRASE_MAP: dict[str, str] = {
    "bachelor degree": "bachelor degree",
    "bachelor of engineering": "bachelor degree",
    "bachelor of science": "bachelor degree",
    "bs degree": "bachelor degree",
    "quality assurance": "quality assurance",
    "quality control": "quality control",
    "process validation": "process validation",
    "root cause analysis": "root cause analysis",
    "root cause": "root cause",
    "design of experiments": "design of experiments",
    "good manufacturing practice": "good manufacturing practice",
    "change control": "change control",
    "risk assessment": "risk assessment",
    "equipment qualification": "equipment qualification",
    "electronic batch records": "electronic batch record",
    "electronic batch record": "electronic batch record",
    "technical writing": "technical writing",
    "statistical analysis": "statistical analysis",
    "continuous improvement": "continuous improvement",
    "cross-functional communication": "cross-functional communication",
    "cross functional communication": "cross-functional communication",
    "cross-functional collaboration": "cross-functional collaboration",
    "cross functional collaboration": "cross-functional collaboration",
    "cross-functional teamwork": "cross-functional collaboration",
    "cross functional teamwork": "cross-functional collaboration",
    "standard operating procedure": "standard operating procedure",
    "standard operating procedures": "standard operating procedure",
    "validation protocol": "process validation protocol",
    "machine learning": "machine learning",
    "cell culture": "cell culture",
    "mammalian cell culture": "mammalian cell culture",
    "microbial culture": "microbial culture",
    "upstream process development": "upstream process development",
    "downstream process development": "downstream process development",
    "process scale-up": "process scale-up",
    "process scale up": "process scale-up",
    "technology transfer": "technology transfer",
    "tech transfer": "technology transfer",
    "aseptic technique": "aseptic technique",
    "aseptic processing": "aseptic processing",
    "protein purification": "protein purification",
    "protein purifications": "protein purification",
    "chromatographic techniques": "chromatography",
    "membrane filtration": "membrane filtration",
    "protein expression": "protein expression",
    "recombinant protein": "recombinant protein",
    "protein biochemistry": "protein biochemistry",
    "data analysis": "data analysis",
    "multivariate data analysis": "multivariate analysis",
    "multivariate analysis": "multivariate analysis",
    "analytical technologies": "analytical technologies",
    "real time": "real time",
}

MAX_PHRASE_TOKENS = 3
MIN_PHRASE_TOKENS = 2
